feat: improve UX for Typescript app codegen
polywrap/wrap-abi-bindgen pull request #40
Opened 2023-07-28 10:38 UTC by Niraj-Kamdar

2023-07-28 14:32 UTC, krisbitney reviewed
This looks good but I think we could reduce the number of getters for each property. I'm guessing you thought a lot about this so maybe I'm missing something.

Since the getter methods are abstract, the user will always implement them. Since they will always be implemented, I think it would make more sense to just make the properties themselves abstract and public, or to remove the properties altogether and just use the methods.

For example,

```ts
/ is this._defaultUri redundant?
private _getUri(uri?: string): string {
  return uri || this._defaultUri || this._getDefaultUri() || "testimport.uri.eth";
}
  // can we do this?
private _getUri(uri?: string): string {
  return uri || this._getDefaultUri() || "testimport.uri.eth";
}
  ```

2023-08-01 13:02 UTC, krisbitney approved these changes

2023-08-15 22:55 UTC, dOrgJelli requested changes
This PR should point to a new PR in the CLI for the updated template project. This way we know what the e2e looks like.

2023-08-15 22:55 UTC, dOrgJelli commented on implementations/app-typescript/src/__tests__/cases/000-sanity/output/types.ts
> +export abstract class BaseTestImport {
This type isn't being used anywhere, is this what the user imports into their code? If so I don't think that's what we want, instead we'd want `import { TestImport } from ...`

2023-08-15 23:18 UTC, dOrgJelli commented
Created a PR here @Niraj-Kamdar https://github.com/polywrap/cli/pull/1855

2023-08-21 00:29 UTC, dOrgJelli approved these changes
:fire:

2023-08-21 00:30 UTC, merged